name = "cricket-scoreboard-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespace for session storage
[[kv_namespaces]]
binding = "SESSIONS"
id = "3466eafd42b74cfbb092fce2a3e6f85a"

[build]
command = ""
